import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="min-h-screen bg-cover bg-center bg-no-repeat bg-fixed"
        style={{ backgroundImage: "url('/chrome-bg.jpeg')" }}
      >
        <Navbar />
        {/*  <BubbleBackground />*/}
        <main className="">{children}</main>
      </body>
    </html>
  );
}
